### PR TITLE
fix: api exception not render JsonResponse

### PR DESCRIPTION
**Pull request by axmad386**
This PR should fix some bug regarded rendering ApiException and ApiValidationException to JsonResponse

### CODE REVIEW

**Comment by axmad386** [comment]
Test result:
```
❯ date && git branch --show-current && composer test
Thu Dec 22 01:55:23 PM WIB 2022
exception-response
> php-cs-fixer fix --allow-risky=yes
Loaded config default from "/home/dmuggle/GIT/laravel-api-response/.php-cs-fixer.php".
Using cache file ".php-cs-fixer.cache".

Fixed all files in 0.001 seconds, 16.000 MB memory used
> pest --stop-on-failure

   PASS  Tests\ApiExceptionTest
  ✓ it can handle ApiException
  ✓ it returns HTTP_BAD_REQUEST for ApiException by default
  ✓ it can handle ApiValidationException
  ✓ it can access route with validated parameters

   PASS  Tests\ApiResponseTest
  ✓ it returns correct response header
  ✓ it returns correct json structure for success api response
  ✓ it returns correct json structure for error api response
  ✓ it can handle data of type ResourceCollection|JsonResource|Collection
  ✓ it fails when the argument $data is not valid
  ✓ it fails when the argument $errors is not valid

   PASS  Tests\ExceptionHandlerTest
  ✓ it render an api response when exception is thrown
  ✓ it does not display message and stack traces on production
  ✓ it does not display traces when 404 not found exception is thrown
  ✓ it can still return json response if exception handler is not configured
  ✓ it only display traces when response status code in [400, 502, 500]
  ✓ it return 401 for laravel authentication exception
  ✓ it return 404 for laravel model not found exception

  Tests:  17 passed
  Time:   0.18s

```

**Comment by lakuapik** [comment]
@axmad386 wow!! thanks a lot!

**Comment by lakuapik** [comment]
@axmad386 this is a breaking change, because a return type was changed, user who already extend the exception will get an error.

i will plan this to be released in v2. also, i was planning to rewrite the api response class as json response for compatibility.

**Comment by axmad386** [comment]
How about to maintain the current return type. I think i can do this by modify little bit

Just want to support people that already use this current version @lakuapik

**Comment by axmad386** [comment]
@lakuapik can we discuss this more on discord channel?

**Comment by lakuapik** [comment]
@axmad386 sure!

**Comment by axmad386** [comment]
I will close this PR since it's impossible to avoid return type changes. For workaround is #16. This is the best we can do for v1 :disappointed:

**Comment by lakuapik** [comment]
@axmad386 thank you for your hard effort, appreciated it!

**Pull request closed without merging**
